updated bats packages
FossilOrigin-Name: 36feb3953cd16f10ba1b09ad7c398822e54fda6830399c970a8612b3e8a51b10

diff --git a/tests/.bats-battery/bats-core/libexec/bats-core/bats b/tests/.bats-battery/bats-core/libexec/bats-core/bats
--- a/tests/.bats-battery/bats-core/libexec/bats-core/bats
+++ b/tests/.bats-battery/bats-core/libexec/bats-core/bats
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 set -e
 
-export BATS_VERSION='1.8.0'
+export BATS_VERSION='1.9.0'
 VALID_FORMATTERS="pretty, junit, tap, tap13"
 
 version() {
@@ -40,11 +40,22 @@ HELP_TEXT_HEADER
                             A two character string of code quote delimiters
                             or 'custom' which requires setting $BATS_BEGIN_CODE_QUOTE and 
                             $BATS_END_CODE_QUOTE. Can also be set via $BATS_CODE_QUOTE_STYLE
+  --line-reference-format   Controls how file/line references e.g. in stack traces are printed:
+                              - comma_line (default): a.bats, line 1
+                              - colon:  a.bats:1
+                              - uri: file:///tests/a.bats:1
+                              - custom: provide your own via defining bats_format_file_line_reference_custom
+                                        with parameters <filename> <line>, store via `printf -v "$output"`
   -f, --filter <regex>      Only run tests that match the regular expression
   --filter-status <status>  Only run tests with the given status in the last completed (no CTRL+C/SIGINT) run.
                             Valid <status> values are:
                               failed - runs tests that failed or were not present in the last run
                               missed - runs tests that were not present in the last run
+  --filter-tags <comma-separated-tag-list>
+                            Only run tests that match all the tags in the list (&&).
+                            You can negate a tag via prepending '!'.
+                            Specifying this flag multiple times allows for logical or (||):
+                            `--filter-tags A,B --filter-tags A,!C` matches tags (A && B) || (A && !C)
   -F, --formatter <type>    Switch between formatters: pretty (default),
                               tap (default w/o term), tap13, junit, /<absolute path to formatter>
   --gather-test-outputs-in <directory>
@@ -79,7 +90,11 @@ HELP_TEXT_BODY
 expand_path() {
   local path="${1%/}"
   local dirname="${path%/*}"
+  if [[ -z "$dirname" ]]; then
+    dirname=/
+  fi
   local result="$2"
+  local OLDPWD="$PWD"
 
   if [[ "$dirname" == "$path" ]]; then
     dirname="$PWD"
@@ -106,6 +121,7 @@ export BATS_RUN_TMPDIR=
 export BATS_GUARANTEED_MINIMUM_VERSION=0.0.0
 export BATS_LIB_PATH=${BATS_LIB_PATH-/usr/lib/bats}
 BATS_REPORT_OUTPUT_DIR=${BATS_REPORT_OUTPUT_DIR-.}
+export BATS_LINE_REFERENCE_FORMAT=${BATS_LINE_REFERENCE_FORMAT-comma_line}
 
 if [[ ! -d "${BATS_TMPDIR}" ]]; then
   printf "Error: BATS_TMPDIR (%s) does not exist or is not a directory" "${BATS_TMPDIR}" >&2
@@ -178,7 +194,7 @@ while [[ "$#" -ne 0 ]]; do
     ;;
   --report-formatter)
     shift
-    if [[ $1 =~ ^(cat|pretty|junit|tap|tap13)$ ]]; then
+    if [[ $1 =~ ^(cat|pretty|junit|tap|tap13|/.*)$ ]]; then
       report_formatter="$1"
     else
       printf "Unknown report formatter '%s', valid options are %s\n" "$1" "${VALID_FORMATTERS}"
@@ -262,6 +278,10 @@ while [[ "$#" -ne 0 ]]; do
     shift
     flags+=('--filter-tags' "$1")
     ;;
+  --line-reference-format)
+    shift
+    BATS_LINE_REFERENCE_FORMAT=$1
+    ;;
   -*)
     abort "Bad command line option '$1'"
     ;;
@@ -271,6 +291,10 @@ while [[ "$#" -ne 0 ]]; do
   esac
   shift
 done
+
+if [[ ! $BATS_LINE_REFERENCE_FORMAT =~ (custom|comma_line|colon|uri) ]]; then
+  abort "Invalid BATS_LINE_REFERENCE_FORMAT '$BATS_LINE_REFERENCE_FORMAT' (e.g. via --line-reference-format)"
+fi
 
 if [[ -n "${BATS_RUN_TMPDIR:-}" ]]; then
   if [[ -d "$BATS_RUN_TMPDIR" ]]; then
@@ -455,9 +479,22 @@ trap 'BATS_INTERRUPTED=true' INT # let the lower levels handle the interruption
 
 set -o pipefail execfail
 
+# pipe stdin into command and to stdout
+# pipe command stdout to file
+bats_tee() { # <output-file> <command...>
+  local output_file=$1 status=0
+  shift
+  exec 3<&1 # use FD3 to get around pipe
+  tee >(cat >&3) | "$@" >"$output_file" || status=$?
+  if (( status != 0 )); then
+    printf "ERROR: command \`%s\` failed with status %d\n" "$*" "$status" >&2
+  fi
+  return $status
+}
+
 if [[ -n "$report_formatter" ]]; then
   exec bats-exec-suite "${flags[@]}" "${filenames[@]}" |
-    tee >("$interpolated_report_formatter" "${report_formatter_flags[@]}" >"${BATS_REPORT_OUTPUT_DIR}/${BATS_REPORT_FILENAME}") |
+    bats_tee "${BATS_REPORT_OUTPUT_DIR}/${BATS_REPORT_FILENAME}" "$interpolated_report_formatter" "${report_formatter_flags[@]}" |
     bats_test_count_validator |
     "$interpolated_formatter" "${formatter_flags[@]}"
 else
diff --git a/tests/.bats-battery/bats-core/libexec/bats-core/bats-exec-file b/tests/.bats-battery/bats-core/libexec/bats-core/bats-exec-file
--- a/tests/.bats-battery/bats-core/libexec/bats-core/bats-exec-file
+++ b/tests/.bats-battery/bats-core/libexec/bats-core/bats-exec-file
@@ -92,7 +92,7 @@ bats_run_setup_file() {
   local status=0
   # get the setup_file/teardown_file functions for this file (if it has them)
   # shellcheck disable=SC1090
-  source "$BATS_TEST_SOURCE" >>"$BATS_OUT" 2>&1
+  source "$BATS_TEST_SOURCE"
 
   BATS_SOURCE_FILE_COMPLETED=1
 
@@ -118,6 +118,7 @@ bats_run_teardown_file() {
   fi
 }
 
+# shellcheck disable=SC2317
 bats_file_teardown_trap() {
   bats_run_teardown_file
   bats_file_exit_trap in-teardown_trap
@@ -126,6 +127,7 @@ bats_file_teardown_trap() {
 # shellcheck source=lib/bats-core/common.bash
 source "$BATS_ROOT/lib/bats-core/common.bash"
 
+# shellcheck disable=SC2317
 bats_file_exit_trap() {
   local -r last_return_code=$?
   if [[ ${1:-} != in-teardown_trap ]]; then
@@ -134,7 +136,12 @@ bats_file_exit_trap() {
   trap - ERR EXIT
   local failure_reason
   local -i failure_test_index=$((BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE + 1))
-  if [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
+  if [[ -n "${BATS_TEST_SKIPPED-}" ]]; then
+    export BATS_TEST_SKIPPED # indicate to exec-test that it should skip
+    # print skip message for each test (use this to avoid reimplementing filtering)
+    bats_run_tests 1<&3 # restore original stdout (this is running in setup_file's redirection to BATS_OUT)
+    bats_exec_file_status=0 # this should not lead to errors
+  elif [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
     if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
       failure_reason='setup_file'
     elif [[ -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
@@ -160,7 +167,7 @@ bats_file_exit_trap() {
     bats_generate_warning 3 --no-stacktrace "$BATS_TEST_FILENAME"
   fi
 
-  exit $bats_exec_file_status
+  exit "$bats_exec_file_status"
 }
 
 function setup_file() {
@@ -221,6 +228,7 @@ bats_run_test_with_retries() { # <args>
       status=$?
       if ((status == BATS_RETRY_RETURN_CODE)); then
         should_try_again=1
+        status=0 # this is not the last try -> reset status
       else
         should_try_again=0
         bats_exec_file_status=$status
@@ -285,6 +293,25 @@ bats_read_tests_list_file() {
 bats_run_tests() {
   bats_exec_file_status=0
 
+  if [[ "${BATS_RUN_TESTS_SKIPPED-}" ]]; then
+    # shellcheck disable=SC2317
+    bats_test_begin() {
+      printf "ok %d %s # skip %s\n" "$test_number_in_suite" "$1" "$BATS_RUN_TESTS_SKIPPED_REASON"  >&3
+      return 1
+    }
+    local test_number_in_suite=0
+    for test_name in "${tests_to_run[@]}"; do
+      ((++test_number_in_suite))
+      eval "$test_name" || true
+    done
+    exit 0
+  fi
+
+  if [[ "$num_jobs" -lt 1 ]]; then
+    printf 'Invalid number of jobs: %s\n' "$num_jobs" >&2
+    exit 1
+  fi
+
   if [[ "$num_jobs" != 1 && "${BATS_NO_PARALLELIZE_WITHIN_FILE-False}" == False ]]; then
     export BATS_SEMAPHORE_NUMBER_OF_SLOTS="$num_jobs"
     bats_run_tests_in_parallel "$BATS_RUN_TMPDIR/parallel_output" || bats_exec_file_status=1
@@ -297,7 +324,7 @@ bats_run_tests() {
         break
       fi
       # Only handle non-empty lines
-      if [[ $test_name ]]; then
+      if [[ -n ${test_name-} ]]; then
         ((++test_number_in_suite))
         ((++test_number_in_file))
         bats_run_test_with_retries "${flags[@]}" "$filename" "$test_name" \
diff --git a/tests/.bats-battery/bats-core/libexec/bats-core/bats-exec-suite b/tests/.bats-battery/bats-core/libexec/bats-core/bats-exec-suite
--- a/tests/.bats-battery/bats-core/libexec/bats-core/bats-exec-suite
+++ b/tests/.bats-battery/bats-core/libexec/bats-core/bats-exec-suite
@@ -97,9 +97,8 @@ while [[ "$#" -ne 0 ]]; do
 done
 
 if [[ "$num_jobs" != 1 ]]; then
-  if ! type -p parallel >/dev/null && [[ -z "$bats_no_parallelize_across_files" ]]; then
+  if ! type -p parallel >/dev/null && parallel --version &>/dev/null && [[ -z "$bats_no_parallelize_across_files" ]]; then
     abort "Cannot execute \"${num_jobs}\" jobs without GNU parallel"
-    exit 1
   fi
   # shellcheck source=lib/bats-core/semaphore.bash
   source "${BATS_ROOT}/lib/bats-core/semaphore.bash"
@@ -108,7 +107,7 @@ fi
 
 # create a file that contains all (filtered) tests to run from all files
 TESTS_LIST_FILE="${BATS_RUN_TMPDIR}/test_list_file.txt"
-
+focus_mode=
 bats_gather_tests() {
   local line test_line tags
   all_tests=()
@@ -131,6 +130,23 @@ bats_gather_tests() {
         line="${BASH_REMATCH[2]}"
       else
         tags=()
+      fi
+      # is this test focused?
+      if bats_all_in tags 'bats:focus'; then
+        if [[ $focus_mode == 1 ]]; then
+          # focused tests in focus mode should just be registered
+          :
+        else
+          # the current test enables focus mode ...
+          focus_mode=1
+          # ... -> remove previously found, unfocused tests
+          all_tests=()
+          : > "$TESTS_LIST_FILE"
+        fi
+      elif [[ $focus_mode == 1 ]]; then
+        # the current test is not focused but focus mode is enabled -> filter out
+        continue
+        # no else -> unfocused tests outside focus mode should just be registered
       fi
       if [[ ${#filter_tags_list[@]} -gt 0 ]]; then
         local match=
@@ -197,6 +213,10 @@ else
   # use UTC (-u) to avoid problems with TZ changes
   BATS_RUNLOG_DATE=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
   export BATS_RUNLOG_FILE="$BATS_RUN_LOGS_DIRECTORY/${BATS_RUNLOG_DATE}.log"
+  if [[ ! -w "$BATS_RUN_LOGS_DIRECTORY" ]]; then
+    printf "WARNING: Cannot write in %s. This run will not write a log!\n" "$BATS_RUN_LOGS_DIRECTORY" >&2
+    BATS_RUNLOG_FILE='/dev/null' # disable runlog file
+  fi
 fi
 
 bats_gather_tests "$@"
@@ -289,16 +309,18 @@ fi
 
 if [[ -n "$bats_no_parallelize_across_files" ]] && [[ ! "$num_jobs" -gt 1 ]]; then
   abort "The flag --no-parallelize-across-files requires at least --jobs 2"
-  exit 1
 fi
 
 if [[ -n "$bats_no_parallelize_within_files" ]] && [[ ! "$num_jobs" -gt 1 ]]; then
   abort "The flag --no-parallelize-across-files requires at least --jobs 2"
-  exit 1
 fi
 
 # only abort on the lowest levels
 trap 'BATS_INTERRUPTED=true' INT
+
+if [[ -n "$focus_mode" ]]; then
+  printf "WARNING: This test run only contains tests tagged \`bats:focus\`!\n"
+fi
 
 bats_exec_suite_status=0
 printf '1..%d\n' "${test_count}"
@@ -328,6 +350,7 @@ trap bats_suite_exit_trap EXIT
 
 exec 3<&1
 
+# shellcheck disable=SC2317
 bats_suite_exit_trap() {
   local print_bats_out="${BATS_SHOW_OUTPUT_OF_SUCCEEDING_TESTS}"
   if [[ -z "${BATS_SETUP_SUITE_COMPLETED}" || -z "${BATS_TEARDOWN_SUITE_COMPLETED}" ]]; then
@@ -354,7 +377,7 @@ bats_suite_exit_trap() {
 
   if [[ -d "$BATS_RUN_LOGS_DIRECTORY" && -n "${BATS_INTERRUPTED:-}" ]]; then
     # aborting a test run with CTRL+C does not save the runlog file
-    rm "$BATS_RUNLOG_FILE"
+    [[ "$BATS_RUNLOG_FILE" != /dev/null ]] && rm "$BATS_RUNLOG_FILE"
   fi
   exit "$bats_exec_suite_status"
 } >&3
@@ -375,6 +398,7 @@ bats_run_teardown_suite() {
   fi
 }
 
+# shellcheck disable=SC2317
 bats_teardown_suite_trap() {
   bats_run_teardown_suite
   bats_suite_exit_trap
@@ -431,4 +455,13 @@ fi
 set -eET
 bats_run_teardown_suite
 
-exit "$bats_exec_suite_status"
+if [[ "$focus_mode" == 1 && $bats_exec_suite_status -eq 0 ]]; then 
+  if [[ ${BATS_NO_FAIL_FOCUS_RUN-} == 1 ]]; then
+    printf "WARNING: This test run only contains tests tagged \`bats:focus\`!\n"
+  else
+    printf "Marking test run as failed due to \`bats:focus\` tag. (Set \`BATS_NO_FAIL_FOCUS_RUN=1\` to disable.)\n" >&2
+    bats_exec_suite_status=1
+  fi
+fi
+
+exit "$bats_exec_suite_status" # the actual exit code will be set by the exit trap using bats_exec_suite_status
